"""
Web3 service – connects to the local Hardhat node (or Sepolia).
Reads contract ABIs from the artifacts auto-generated by Hardhat.
"""

import json
import logging
from pathlib import Path

from web3 import Web3
from app.core.config import get_settings

logger = logging.getLogger(__name__)

settings = get_settings()

# ── Connection ────────────────────────────────────────────────────────────────

w3: Web3 = Web3(Web3.HTTPProvider(settings.WEB3_RPC_URL))

if w3.is_connected():
    logger.info(f"✅ Web3 connected to {settings.WEB3_RPC_URL}  (chain id: {w3.eth.chain_id})")
else:
    logger.warning(f"⚠️  Web3 could NOT connect to {settings.WEB3_RPC_URL}. Using mock mode.")


def _load_abi(path: str) -> list:
    """Load ABI from a Hardhat artifact JSON file."""
    artifact_path = Path(__file__).parent.parent.parent / path
    with open(artifact_path) as f:
        return json.load(f)["abi"]


# ── Contract instances ────────────────────────────────────────────────────────

def get_escrow_contract():
    abi = _load_abi(settings.ESCROW_ABI_PATH)
    return w3.eth.contract(
        address=Web3.to_checksum_address(settings.ESCROW_CONTRACT_ADDRESS),
        abi=abi
    )


def get_binr_contract():
    abi = _load_abi(settings.BINR_ABI_PATH)
    return w3.eth.contract(
        address=Web3.to_checksum_address(settings.BINR_CONTRACT_ADDRESS),
        abi=abi
    )


# ── Read Helpers ──────────────────────────────────────────────────────────────

def get_trust_score(wallet_address: str) -> int:
    """Fetch a user's on-chain trust score from BioLendEscrow."""
    try:
        contract = get_escrow_contract()
        score = contract.functions.trustScores(
            Web3.to_checksum_address(wallet_address)
        ).call()
        return int(score)
    except Exception as e:
        logger.error(f"get_trust_score error: {e}")
        return 0


def get_loan(loan_id: int) -> dict:
    """Fetch loan struct from the smart contract."""
    try:
        contract = get_escrow_contract()
        loan = contract.functions.loans(loan_id).call()
        return {
            "id": loan[0],
            "amount": loan[1],
            "funded_amount": loan[2],
            "interest_amount": loan[3],
            "borrower": loan[4],
            "guardians": list(loan[5]),
            "approvals": loan[6],
            "is_funded": loan[7],
            "is_disbursed": loan[8],
            "is_repaid": loan[9],
            "is_defaulted": loan[10],
            "expires_at": loan[11],
            "deadline": loan[12],
        }
    except Exception as e:
        logger.error(f"get_loan error: {e}")
        return {}


def is_wallet_locked(wallet_address: str) -> bool:
    """Check whether a wallet is SMS-locked on-chain."""
    try:
        contract = get_escrow_contract()
        return contract.functions.isLocked(
            Web3.to_checksum_address(wallet_address)
        ).call()
    except Exception as e:
        logger.error(f"is_wallet_locked error: {e}")
        return False


# ── Write Helpers (Backend Admin Signed Txns) ─────────────────────────────────

def _sign_and_send(fn_call) -> str:
    """Generic helper: build, sign, and broadcast a transaction as the backend admin."""
    account = w3.eth.account.from_key(settings.BACKEND_WALLET_PRIVATE_KEY)
    tx = fn_call.build_transaction({
        "from": account.address,
        "nonce": w3.eth.get_transaction_count(account.address),
        "gas": 300_000,
        "gasPrice": w3.eth.gas_price,
    })
    signed = w3.eth.account.sign_transaction(tx, settings.BACKEND_WALLET_PRIVATE_KEY)
    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)
    return receipt.transactionHash.hex()


def set_wallet_lock(wallet_address: str, lock_status: bool) -> str:
    """
    Backend admin locks/unlocks a wallet on-chain.
    Called by the SMS Lock webhook when the user SMSs 'LOCK WALLET'.
    """
    contract = get_escrow_contract()
    fn = contract.functions.setWalletLock(
        Web3.to_checksum_address(wallet_address), lock_status
    )
    return _sign_and_send(fn)


def mark_loan_default(loan_id: int) -> str:
    """Backend admin marks a loan as defaulted after deadline passes."""
    contract = get_escrow_contract()
    fn = contract.functions.markDefault(loan_id)
    return _sign_and_send(fn)
